name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe the problem and your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? Describe the use case.
      placeholder: I'm trying to ... but currently ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about.
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of Cerno does this relate to?
      options:
        - Atomic layer (parsing, file watching)
        - Short-term layer (insights, clustering, confidence)
        - Long-term layer (principles, linking, lifecycle)
        - Pipeline processes (Accumulator, Reconciler, Organiser, Resolver)
        - CLI
        - API
        - Documentation
        - Other
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples.
    validations:
      required: false
