defmodule Cerno.Formatter.Claude do
  @moduledoc """
  Formatter for Claude agent (CLAUDE.md format).

  Produces a markdown section suitable for injection into a CLAUDE.md file.
  Principles are grouped by domain and ordered by rank.
  """

  @behaviour Cerno.Formatter

  @section_heading "## Resolved Knowledge from Cerno"
  @max_tokens 4000

  @impl true
  def format_sections(principles, opts \\ []) do
    include_metadata? = Keyword.get(opts, :include_metadata, false)

    grouped =
      principles
      |> Enum.sort_by(& &1.rank, :desc)
      |> Enum.group_by(&primary_domain/1)

    sections =
      grouped
      |> Enum.sort_by(fn {_domain, ps} -> -length(ps) end)
      |> Enum.map(fn {domain, ps} ->
        items =
          ps
          |> Enum.map(fn p ->
            base = "- #{p.content}"

            if include_metadata? do
              base <> " *(confidence: #{Float.round(p.confidence, 2)}, rank: #{Float.round(p.rank, 2)})*"
            else
              base
            end
          end)
          |> Enum.join("\n")

        "### #{domain}\n\n#{items}"
      end)
      |> Enum.join("\n\n")

    """
    #{@section_heading}

    > Auto-generated by Cerno. Do not edit manually — this section is overwritten on each resolution.

    #{sections}
    """
    |> String.trim()
  end

  @impl true
  def max_output_tokens, do: @max_tokens

  defp primary_domain(principle) do
    case principle.domains do
      [first | _] -> String.capitalize(first)
      _ -> "General"
    end
  end
end
